### ISSUE TITLE
An error is reported during the test：“make test”

### ISSUE THREAD

**Issue by vegetable-rocket** [VIS4ROB-lab/dmce#3]
![image](https://github.com/user-attachments/assets/b70adc04-1d4e-449f-8e96-a0af5e92fea2)
How to solve it？

**Comment by seanbone** [comment]
Hi, I need a bit more information in order to help you. What operating system are you on? Are you able to compile the docker image and ROS package without errors using `make build-docker build-pkg`? What debugging steps have you tried already?

I recommend you take a look at `dmce_tests/CMakeLists.txt`. Some further reading on rostest:

http://wiki.ros.org/rostest/Writing

http://wiki.ros.org/gtest

**Comment by vegetable-rocket** [comment]
Hello, I am using Windows, and I am operating under Ubuntu 20.04 in VMware. I can compile the docker image using make build-docker, but make build-pkg will report an error:
![image](https://github.com/user-attachments/assets/24f42c3a-1eb7-4046-b625-ab0db1bbce91)
I checked the Makefile and couldn't find the problem
![image](https://github.com/user-attachments/assets/d32053be-7b4b-481c-9441-088dfb8da018)

Because I am a beginner, the debugging is limited. I will take a look at the information you provided. Thank you for your reply！

**Comment by seanbone** [comment]
Some additional tips:
- If you're unfamiliar with Docker, I recommend reading a bit about it. Particularly [docker volumes](https://docs.docker.com/storage/volumes/). Docker is not strictly required to run this project but it allows you to run it without installing ROS locally.
- Catkin is the build system used by ROS. Again I recommend getting familiari with it first and perhaps making a test project of your own before trying to run this one which is fairly complex. [Online tutorials](http://wiki.ros.org/catkin/Tutorials).
- make sure the `GIT` and `CATKIN_WS` variables in the project's Makefile are set to the appropriate directories in your Ubuntu VM, and that they exist.
- `make bash` will open an interactive bash session in the Docker container, which can help with debugging.

**Comment by vegetable-rocket** [comment]
Thank you for your reply, I'll try them.
